### PR TITLE
Argument defaults changed

### PR DESCRIPTION
**Pull request by sagun98**
Hi Lauren, 
Please let me know if anything needs to be changed here. 

Updated 4 default options to: 
1. --input: os.getcwd()+"/input/"
2. --config: os.getcwd()+"/etc/
3. --scripts: os.getcwd()+"/src/"
4. --temp: os.getcwd()+"/temp/"
No changes to output options as it is required.

### CODE REVIEW

**Comment by ljmciver** [comment]
Hi @sagun98 , Thank you for the PR! Here are a couple suggestions. Let me know your thoughts on them!
1. Would you consider using "os.path.join" instead of "/" so the directory path will work with multiple platforms?
2. Do you think we should change "temp" to "tmp" to be similar to a system folder name?
3. Can you add one line to this cli.py module that adds the args.scripts folder to the users $PATH so these scripts are available to call directly from a workflow without the user having to install them?
4. I think we want the scripts folder to be relative to the workflow file instead of the current working directory. I am not sure exactly how to get the path of the workflow file. You might be able to get it with the following. Test it out and let me know how it goes. It might return the location of the workflow definition (in the AnADAMA2 package) not the workflow instance (in the workflow run.py example script in the tutorial).
```
import inspect
workflow_path=inspect.getfile(cls)
```

Please let me know if you have any questions.

Thank you!

**Comment by sagun98** [comment]
Hi @ljmciver , 
Thank you so much for the details. I have updated the following: 
1. Using "os.path.join" instead of "/" so the directory path will work with multiple platforms.
2. Changed "temp" to "tmp" to be similar to a system folder name
3. Added one line to this cli.py module that adds the args.scripts folder to the users $PATH so these scripts are available to call directly from a workflow without the user having to install them.

Please let me know if any issues. 

https://github.com/biobakery/anadama2/pull/4/files

**Comment by ljmciver** [comment]
Thank you @sagun98 ! This all looks great. Would you consider making one last change? Add a global variable:
``` SCRIPTS_FOLDER = os.pathsep + os.path.join(os.getcwd(),"src")``` and use SCRIPTS_FOLDER in the path change and the default for the option. This way if we ever want to change the location, we just change it in the one variable instead of having to change it in two places.

Thanks again!

**Comment by ljmciver** [comment]
Hi @sagun98 , I just realized we will need to move the `os.environ['PATH'] +=` statement to further down in the code and provide it with the "args.src" variable so if a user changes this parameter it will get set. Please let me know if you have any questions!

Thanks!
Lauren

**Comment by sagun98** [comment]
Hi @ljmciver , 
Sure thing, thank you so much for the review. 

1. I added `SCRIPTS_FOLDER = os.pathsep + os.path.join(os.getcwd(),"src")` and used `SCRIPTS_FOLDER` in the path change and the default for the option. 

2. Thank you for catching this. Totally makes sense. I added the following line in `workflow.py` because we do not have access to the `args.scripts` or `self.vars.get("scripts")` values in "cli.py" script. Please let me know if you feel like we need to move this to `default option init` rather than `workflow init` file. 

```
os.environ['PATH']+=os.pathsep+os.path.join(self.vars.get("scripts"))
```

**Comment by ljmciver** [comment]
Hi @sagun98 , Thanks for the changes! Sorry where to put it is a tricky one. If you add it around line 770 in the "go" function it should work and it will not try to gather the arguments too early in the process. Also you can totally remove the global variable now that we have to move the PATH statement. That can go back to `default=os.path.join(os.getcwd(),"src")` for the scripts argument. 

Thank you for iterating! I am still trying to figure out if there is a way to get the file location of the calling script! I will let you know if I figure something out. I saw the same thing you did with "inspect". Thank again for trying it.

Thanks!
Lauren

**Comment by sagun98** [comment]
Hi @ljmciver, 
Thank you for the review again. I have moved the PATH line around line "770" go function and tested the anadama2 workflow. Also, the Global variable was removed and replaced with  `default=os.path.join(os.getcwd(),"src")`. 
Please let me know if anything else needs to be changed or if any issues.  

Awesome, many thanks for looking into a way to get the file location of the calling script.

**Comment by ljmciver** [comment]
Hi @sagun98 , Thank you! Looks great! I finally figured out how to get the location of the main workflow script (eg run.py in the analysis workflow repository). Here is the commit: https://github.com/biobakery/anadama2/commit/ec6f2ff17035bbb8d7f65bd4ad824e455b43f6da

If you want to change the default location of "args.scripts=MAIN_PATH" I think you should be set! Try it out with "$ python run.py --help" and you should see the default expected. I tested it out from a couple different directories with AnADAMA2 with this change installed. Please let me know if you have any questions!

Thanks!
Lauren

**Comment by sagun98** [comment]
Hi @ljmciver , 
Thank you so much for looking into getting the location of the main workflow script. This is awesome. I just changed the default PATH to "args.scripts=MAIN_PATH/src" and tested the changes in Analaysis-workflow repo and everything looks good. 

Please let me know if any issue.

**Comment by ljmciver** [comment]
Looks great! Thanks @sagun98 !

**Pull request merged**
